#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Task 28 — rehearse the evidence drawer's Live -> Cached -> Demo
# Fixture fallback against the deployed stack (PRD §7.2/§12.2). Run from the
# repo root. Deploys the stack three times with a different Tavily key each
# time, curls the /live route, and checks the rung it reports. Results are
# appended to task28-rehearsal-results.txt for tasks/plan.md's "note the result".
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# stack_name/region come from infra/samconfig.toml
STACK_NAME="${STACK_NAME:-opportunity-engine-skeleton}"
export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-eu-north-1}"
RESULTS="task28-rehearsal-results.txt"
API_URL=""
PROBE_OK=0

record() { printf '%s  %s\n' "$(date -u +%FT%TZ)" "$1" >> "$RESULTS"; }

# deploy_with_key KEY: redeploys the stack with TavilyApiKey=KEY (needs a prior `sam build`).
deploy_with_key() {
  ( cd infra && sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
      --parameter-overrides "TavilyApiKey=$1" )
}

# probe_evidence WANT LABEL: curl the /live route, check status, header and body all say WANT.
probe_evidence() {
  local want="$1" label="$2" headers body code got body_mode retrieved
  headers=$(mktemp); body=$(mktemp)
  code=$(curl -s --max-time 40 -D "$headers" -o "$body" -w '%{http_code}' \
    "${API_URL}competitors/cmp_001/evidence/evd_hn_31781473/live" || echo 000)
  got=$(grep -i '^x-retrieval-mode:' "$headers" | tr -d '\r' | awk '{print $2}' || true)
  body_mode=$(grep -o '"retrieval_mode": *"[a-z_]*"' "$body" | head -1 | sed 's/.*"\([a-z_]*\)"$/\1/' || true)
  retrieved=$(grep -o '"retrieved_at": *"[^"]*"' "$body" | head -1 | sed 's/.*: *"\(.*\)"/\1/' || true)
  say "HTTP $code · X-Retrieval-Mode: ${got:-<missing>} · body retrieval_mode: ${body_mode:-<missing>} · retrieved_at: ${retrieved:-<missing>}"
  if [[ "$code" == 200 && "$got" == "$want" && "$body_mode" == "$want" ]]; then
    printf '  %s✓ PASS%s %s served as %s\n' "$GREEN" "$RESET" "$label" "$want"
    record "PASS  $label -> $want (retrieved_at ${retrieved:-?})"
    PROBE_OK=1
  else
    warn "FAIL: $label expected '$want'"
    record "FAIL  $label expected $want, got HTTP $code header=${got:-none} body=${body_mode:-none}"
    PROBE_OK=0
  fi
  rm -f "$headers" "$body"
}

# stop_if_failed: after a failed probe, let the human bail out instead of stacking more deploys on it.
stop_if_failed() {
  [[ "$PROBE_OK" == 1 ]] && return 0
  confirm "That did not match. Continue to the next stage anyway?" && return 0
  note "Stopped. Results so far are in $RESULTS. Paste them back to Claude."
  exit 1
}

banner "Task 28: evidence drawer fallback rehearsal"

# ── Stage 1: tools + AWS login ──────────────────────────────────────────
stage "Tools and AWS login"
for tool in aws sam curl python; do
  if command -v "$tool" >/dev/null 2>&1; then say "✓ $tool"; else warn "$tool not on PATH"; SKIPPED+=("install $tool, then re-run"); fi
done
if aws sts get-caller-identity >/dev/null 2>&1; then
  say "✓ AWS: $(aws sts get-caller-identity --query Arn --output text)  (region $AWS_DEFAULT_REGION)"
else
  warn "Not logged in to AWS. Log in (aws configure / aws sso login), then re-run this wizard."
  exit 1
fi
if ! aws cloudformation describe-stacks --stack-name "$STACK_NAME" >/dev/null 2>&1; then
  warn "Stack $STACK_NAME not found in $AWS_DEFAULT_REGION. Check infra/samconfig.toml, or run: STACK_NAME=<name> $0"
  exit 1
fi
say "✓ Stack $STACK_NAME exists."
: > "$RESULTS"; record "rehearsal started, stack $STACK_NAME ($AWS_DEFAULT_REGION)"

# ── Stage 2: Tavily key + local dry run ─────────────────────────────────
stage "Tavily key, and a local dry run of the live path"
say "The Lambda needs your real Tavily key for the live rung."
open_url "https://app.tavily.com/home"
step "Copy your API key (starts tvly-). If it is already in .env, just press Enter below."
ask_secret TAVILY_API_KEY "Paste the Tavily API key:"
[[ -n "$TAVILY_API_KEY" ]] || { warn "No key entered. Re-run with a key."; exit 1; }
write_env TAVILY_API_KEY "$TAVILY_API_KEY"
say "Local dry run: real Tavily extract of evd_hn_31781473's Hacker News URL, checking the quote is on the page."
if TAVILY_API_KEY="$TAVILY_API_KEY" python -c "
from backend.fixtures.fixtures import EVIDENCE_SENTRY_NOISE_HN as e
from backend.handlers.competitors_stub import _refetch_live
print('  live re-fetch OK, mode =', _refetch_live(e).retrieval_mode.value)"; then
  record "local dry run: live re-fetch of evd_hn_31781473 OK"
else
  warn "The live path failed locally, so step A below will not say live either."
  note "Read the error above: HTTP error = bad key or quota; 'quote no longer found' = Tavily's extract of that page lacks the quote."
  record "local dry run: live re-fetch of evd_hn_31781473 FAILED"
  confirm "Continue to the deploys anyway?" || { note "Stopped. Paste $RESULTS and the error back to Claude."; exit 1; }
fi

# ── Stage 3: A) real key -> live ────────────────────────────────────────
stage "A) Real key: expect LIVE (this also fills the S3 cache)"
say "Builds and deploys with your real key. Takes a few minutes."
confirm "Deploy to stack $STACK_NAME now?" || { note "Skipped, nothing changed."; exit 0; }
( cd infra && sam build --template-file api-gateway.yaml )
deploy_with_key "$TAVILY_API_KEY"
API_URL=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" \
  --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text)
say "API: $API_URL"
probe_evidence live "A: real Tavily key"
stop_if_failed

# ── Stage 4: B) bad key -> cached ───────────────────────────────────────
stage "B) Bad key: expect CACHED"
say "Redeploys with the key bad. Live fails; the copy saved in step A should be served."
confirm "Deploy the bad key now?" || { note "Skipped."; exit 0; }
deploy_with_key "bad"
probe_evidence cached "B: forced Tavily failure, cache populated"
stop_if_failed

# ── Stage 5: C) empty cache -> demo fixture ─────────────────────────────
stage "C) Empty cache, bad key still in place: expect DEMO FIXTURE"
BUCKET=$(aws cloudformation describe-stack-resource --stack-name "$STACK_NAME" \
  --logical-resource-id EvidenceCacheBucket --query StackResourceDetail.PhysicalResourceId --output text)
say "Cache bucket: $BUCKET"
aws s3 ls "s3://$BUCKET/evidence-cache/" --recursive || true
if confirm "Delete everything under s3://$BUCKET/evidence-cache/ ? (only a cache; the last stage refills it)"; then
  aws s3 rm "s3://$BUCKET/evidence-cache/" --recursive
  probe_evidence demo_fixture "C: forced Tavily failure, cache empty"
  stop_if_failed
else
  SKIPPED+=("Step C (demo_fixture rung) not rehearsed")
  record "SKIPPED C"
fi

# ── Stage 6: put the real key back ──────────────────────────────────────
stage "Restore the real key (do not leave the stack broken for the demo)"
say "The stack currently has the bad key. Restoring yours and re-checking LIVE."
if confirm "Redeploy with the real key now?"; then
  deploy_with_key "$TAVILY_API_KEY"
  probe_evidence live "F: real key restored"
else
  SKIPPED+=("Stack still has TavilyApiKey=bad. Fix: cd infra && sam deploy --parameter-overrides TavilyApiKey=<key>")
fi
note "Results: $RESULTS. Paste its contents back to Claude to close out Task 28."
# ──────────────────────────────────────────────────────────────────────────

finish
