#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Task 6 — skeleton AWS deploy (Opportunity Engine).
# Stands up infra/api-gateway.yaml: the Task 2 API Gateway routes plus the
# Task 6 Step Functions skeleton (one Task state → orchestrator_stub Lambda).
# Amplify Hosting is NOT in scope here — it needs a GitHub App console
# connection and has nothing to host until Task 7's React scaffold exists.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Task 6: skeleton AWS deploy"

# ── Stage 1: AWS CLI v2 ─────────────────────────────────────────────────
stage "AWS CLI v2"
if command -v aws >/dev/null 2>&1; then
  say "Already installed: $(aws --version 2>&1)"
else
  say "AWS CLI isn't on PATH. Trying winget first (no admin prompt beyond the UAC dialog)."
  if command -v winget >/dev/null 2>&1; then
    winget install -e --id Amazon.AWSCLI --accept-source-agreements --accept-package-agreements || true
  fi
  if ! command -v aws >/dev/null 2>&1; then
    warn "Still not on PATH (or winget isn't available)."
    open_url "https://awscli.amazonaws.com/AWSCLIV2.msi"
    step "Run the downloaded installer, then close and reopen this terminal so PATH picks it up."
    pause "Installed and reopened a terminal with 'aws' on PATH?"
  fi
fi
if command -v aws >/dev/null 2>&1; then
  say "✓ aws CLI ready: $(aws --version 2>&1)"
else
  warn "aws still not found — re-run this wizard after installing it."
  SKIPPED+=("AWS CLI install — re-run wizard after installing")
fi

# ── Stage 2: AWS SAM CLI ────────────────────────────────────────────────
stage "AWS SAM CLI"
if command -v sam >/dev/null 2>&1; then
  say "Already installed: $(sam --version 2>&1)"
else
  say "Installing via pip (official, no admin/UAC needed)."
  if command -v pip >/dev/null 2>&1; then
    pip install --upgrade aws-sam-cli || true
  fi
  if ! command -v sam >/dev/null 2>&1; then
    warn "pip install didn't put 'sam' on PATH."
    open_url "https://github.com/aws/aws-sam-cli/releases/latest"
    step "Download aws-sam-cli-windows-x86_64.msi from the latest release and run it, then reopen this terminal."
    pause "Installed and reopened a terminal with 'sam' on PATH?"
  fi
fi
if command -v sam >/dev/null 2>&1; then
  say "✓ sam CLI ready: $(sam --version 2>&1)"
else
  warn "sam still not found — re-run this wizard after installing it."
  SKIPPED+=("AWS SAM CLI install — re-run wizard after installing")
fi

# ── Stage 3: AWS credentials + region ───────────────────────────────────
stage "AWS credentials"
say "Long-lived access keys (fastest for a hackathon) or AWS SSO — your call."
if command -v aws >/dev/null 2>&1 && aws sts get-caller-identity >/dev/null 2>&1; then
  say "✓ Already authenticated as: $(aws sts get-caller-identity --query Arn --output text 2>/dev/null)"
else
  if confirm "Use AWS SSO instead of a long-lived access key pair?"; then
    say "This runs 'aws configure sso' — it opens a browser to your IAM Identity Center start URL."
    pause "Have your SSO start URL and SSO region ready, then press Enter to launch it."
    aws configure sso || warn "aws configure sso exited non-zero — you may need to re-run it."
    step "Note the profile name it created; export AWS_PROFILE=<that name> before deploying if it's not 'default'."
  else
    open_url "https://console.aws.amazon.com/iam/home#/security_credentials"
    step "Under 'Access keys', create a new access key (or reuse one you already saved) and copy both values."
    ask_secret AWS_ACCESS_KEY_ID "Paste the Access Key ID:"
    ask_secret AWS_SECRET_ACCESS_KEY "Paste the Secret Access Key:"
    aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    say "✓ written to the AWS CLI's own credential store (~/.aws/credentials) — not to .env."
  fi
fi
ask AWS_REGION "AWS region to deploy into (e.g. us-east-1):"
aws configure set region "$AWS_REGION"
write_env AWS_REGION "$AWS_REGION"
if aws sts get-caller-identity >/dev/null 2>&1; then
  say "✓ Authenticated as: $(aws sts get-caller-identity --query Arn --output text 2>/dev/null)"
else
  warn "Still not authenticated — re-run this wizard once credentials are sorted."
fi

# ── Stage 4: Bedrock model access ───────────────────────────────────────
stage "Bedrock model access (Haiku 4.5 / Sonnet 4.6)"
say "PRD §17.2 needs both models in this region. LEARNING.md Day 1 has a blank"
say "for this — fill it in once you've confirmed it here."
open_url "https://${AWS_REGION}.console.aws.amazon.com/bedrock/home?region=${AWS_REGION}#/modelaccess"
step "Confirm both Claude Haiku 4.5 and Claude Sonnet 4.6 show 'Access granted'."
step "If not, select them and submit the access request (usually instant for Anthropic models)."
if confirm "Both models show 'Access granted' in $AWS_REGION?"; then
  say "✓ Bedrock access confirmed in $AWS_REGION."
  write_env BEDROCK_REGION "$AWS_REGION"
else
  warn "Not granted yet — deploy can continue, but agent Lambdas (Day 2+) will fail Bedrock calls until this clears."
  SKIPPED+=("Bedrock model access in $AWS_REGION — confirm before Day 2 agent work")
fi

# ── Stage 5: sam build + deploy ─────────────────────────────────────────
stage "sam build && sam deploy"
say "Building infra/api-gateway.yaml (API Gateway routes + the Task 6 Step"
say "Functions skeleton: one Task state → orchestrator_stub Lambda)."
say "Clearing stale .aws-sam build output first — CodeUri is the repo root,"
say "so a leftover .aws-sam re-zips itself into the next build and snowballs"
say "the upload (Task 33: 1.5GB for a one-route change)."
rm -rf .aws-sam infra/.aws-sam
( cd infra && sam build --template-file api-gateway.yaml )
say "Now the guided deploy — it'll ask for a stack name, confirm the region,"
say "and ask to auto-create the IAM role SAM needs. Accept defaults unless you"
say "have a reason not to; this creates real, billable (near-free at this"
say "scale) AWS resources."
ask STACK_NAME "Stack name to use (e.g. opportunity-engine-skeleton):"
( cd infra && sam deploy --guided --stack-name "$STACK_NAME" --template-file api-gateway.yaml )
if confirm "Did sam deploy finish with CREATE_COMPLETE / UPDATE_COMPLETE?"; then
  say "Reading stack outputs..."
  API_URL=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text 2>/dev/null || true)
  ORCHESTRATOR_ARN=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='SkeletonOrchestratorArn'].OutputValue" --output text 2>/dev/null || true)
  [[ -n "$API_URL" ]] && write_env API_BASE_URL "$API_URL"
  [[ -n "$ORCHESTRATOR_ARN" ]] && write_env SKELETON_ORCHESTRATOR_ARN "$ORCHESTRATOR_ARN"
  say "✓ API Gateway URL: ${API_URL:-<not found — check the CloudFormation console>}"
  say "✓ Step Functions ARN: ${ORCHESTRATOR_ARN:-<not found — check the CloudFormation console>}"
  note "Task 6's 'skeleton deployed' checkpoint is done. Amplify Hosting is separate"
  note "(Task 7 — needs a GitHub App console connection, and nothing to host until"
  note "the React scaffold exists)."
else
  SKIPPED+=("sam deploy for stack $STACK_NAME — check 'sam deploy' output above and re-run")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
